### PR TITLE
Use daemon threads for NodeChecker and IdleConnectionReaper.

### LINKED ISSUE #278: NodeChecker and IdleConnectionReaper - non-daemon threads
Both NodeChecker and IdleConnectionReaper use threads that are non-daemon threads.  If you enable node discovery or connection reaping but for whatever reason fail to shutdown a JestClient the JVM hangs.  It seems that these should these should be able to be started as non-daemon threads.  Currently there is not really a hook to do this.

For NodeChecker a simple workaround is to subclass NodeChecker and override executor() and manually register a NodeChecker.  IdleConnectionReaper isn't quite as simple.

Would be nice if one way or another w/ the default JestClientFactory it would be possible to start these as daemon threads.

### PR DESCRIPTION
**Pull request by gilbode**
Resolve #278 by using daemon threads in NodeChecker and IdleConnectionReaper.

### CODE REVIEW

File: jest-common/src/main/java/io/searchbox/client/config/discovery/NodeChecker.java [hunk 1]
```diff
@@ -91,6 +96,28 @@ protected Scheduler scheduler() {
...
+        // Technically this listener is added after start() was called so it is a little gross, but it
+        // is called within doStart() so we know that the service cannot terminate or fail concurrently
+        // with adding this listener so it is impossible to miss an event that we are interested in.
+        addListener(new Listener() {
+            @Override public void terminated(State from) {
+                executor.shutdown();
+            }
+            @Override public void failed(State from, Throwable failure) {
+                executor.shutdown();
+            }}, MoreExecutors.sameThreadExecutor());
```
Comment (kramer) [inline jest-common/src/main/java/io/searchbox/client/config/discovery/NodeChecker.java]: Better to use the non-deprecated equivalent `directExecutor()`.

**Comment by kramer** [comment]
Thank you for your contribution @gilbode !
